baseURL = "https://nharp189.github.io"
languageCode = "en-us"
title = "Nick's Site"
theme = "ananke"

sectionPagesMenu = "main"

  [[menu.main]]
    identifier = "posts"
    name = "Blog Posts"
    pre = "<i class='fa fa-heart'></i>"
    url = "/posts"
    weight = -110

 [[menu.main]]
    identifier = "music"
    name = "Tunes"
    pre = "<i class='fa fa-heart'></i>"
    url = "/music"
    weight = -110
